"""Generate additional training data samples for O.L.I.V.I.A."""
import json
import os

# Change to project directory
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Additional training samples
samples = []

# Anime samples (200 more)
anime_samples = [
    ("What is the Winter 2026 anime lineup like?", "Jujutsu Kaisen: The Culling Game is topping the charts. Lots of sequels this season. Anything specific you're looking forward to?"),
    ("Is Sakamoto Days getting an anime?", "Yeah, it's been announced. The manga's action scenes should translate well to animation. Curious which studio got it."),
    ("What do you think about anime adaptations of manhwa?", "Solo Leveling proved they can work great. Different pacing from manga but the Korean webtoon style translates well to animation."),
    ("Is Re:Zero Season 3 good?", "If you liked the previous seasons, yes. Subaru's still suffering, which is kind of the point. The character development pays off."),
    ("What happened with Toei Animation?", "They're still going strong with One Piece. Had some production issues over the years but they're a massive studio."),
    ("What is the One Piece remake about?", "Reanimating the early arcs with modern production values. WIT Studio's handling it. Good entry point if the original's dated animation put you off."),
    ("Is Spy x Family Season 3 announced?", "Yeah, it's coming. The manga still has plenty of material. More Anya is always welcome."),
    ("What studio animated Toilet-Bound Hanako-kun?", "Lerche did the first season. The art style really captures the manga's unique look. Season 2 looks good too."),
    ("Any good anime movies coming out?", "Depends on what's in theaters near you. Anime films get limited releases outside Japan sometimes. What genre are you into?"),
    ("What makes Jujutsu Kaisen popular?", "Great animation, interesting power system, characters you actually care about. MAPPA really delivered on the action."),
    ("Should I watch My Hero Academia?", "It's good shonen with superhero flavor. Gets better after season 1. Has some pacing issues later but still enjoyable."),
    ("What's Mob Psycho 100 about?", "Psychic kid trying to live a normal life. Same creator as One Punch Man. The animation is incredible, especially season 2."),
    ("Is Gintama funny?", "Hilarious once it gets going. The parody and references require some anime knowledge. Gets emotional too when you least expect it."),
    ("What happened to Studio Ghibli?", "Still making films. Hayao Miyazaki keeps un-retiring. The Boy and the Heron was recent. Legendary studio."),
    ("Is Evangelion worth watching?", "Foundational anime, but divisive. The ending confuses everyone. Rebuild movies are more accessible. Worth seeing either way."),
    ("What's a good slice of life?", "K-On for music and friendship. Nichijou for comedy. Non Non Biyori for countryside relaxation. What vibe?"),
    ("Any anime about music?", "K-On, Beck, Your Lie in April, Bocchi the Rock, Given. Different genres and tones. What kind of music?"),
    ("What's Land of the Lustrous?", "CGI anime done right. Gem people, existential themes, gorgeous visuals. Studio Orange proved CGI can be beautiful."),
    ("Is seasonal anime overwhelming?", "It can be. Don't try to watch everything. Pick a few that interest you. Quality over quantity."),
    ("What anime studio has the best work conditions?", "Kyoto Animation is known for treating staff well. Rare in the industry. Their output reflects the care."),
    ("Why do anime seasons have so many episodes?", "Usually 12-13 episodes per cour. Fits broadcast schedules. Some get 24 for bigger stories."),
    ("Is watching anime on 1.5x speed okay?", "Your time, your choice. Some pacing benefits. Might miss music cues though."),
    ("What's the best anime app?", "Crunchyroll has the most. Netflix for originals. Depends on your region and budget."),
    ("Should I watch anime in release order?", "Usually yes. Some franchises are confusing otherwise. Research the watch order if unsure."),
    ("What anime has good English dub?", "Cowboy Bebop, Fullmetal Alchemist Brotherhood, Dragon Ball Z. Some dubs are excellent."),
    ("Is anime mainstream now?", "More than ever. Attack on Titan and Demon Slayer brought new audiences. Less niche than before."),
    ("What's simulcast?", "Streaming episodes as they air in Japan. Usually same day or week. No more waiting for translations."),
    ("Why do anime openings spoil stuff?", "Japanese audiences don't mind as much. It's about hype not surprise. Skip if you want to avoid it."),
    ("Is light novel anime usually good?", "Varies wildly. Some adapt well, others feel rushed. Source material quality matters."),
    ("What's a good anime to binge?", "Death Note's a classic binge. 37 episodes and gripping throughout. Mob Psycho 100 if you want something lighter."),
    ("What's your opinion on anime remakes?", "Depends on execution. Fruits Basket remake was excellent. Some feel unnecessary. If it brings new fans in, I'm for it."),
    ("Best anime of all time?", "Impossible question. Fullmetal Alchemist Brotherhood is consistently rated highest. But best depends on what you value."),
    ("Is HxH worth watching?", "Hunter x Hunter's excellent. The Chimera Ant arc is some of the best anime out there. Just know it's on indefinite hiatus."),
    ("Why did the anime get cancelled?", "Which anime? Usually it's sales, source material running out, or production issues. Sometimes studios just can't continue."),
    ("What's the best anime streaming service?", "Crunchyroll has the biggest library. Netflix has exclusives. Depends on your region and budget."),
    ("Is Bleach worth finishing?", "Thousand Year Blood War is genuinely great. If you liked Soul Society arc, it returns to form. The final arc delivers."),
    ("What makes MAPPA different?", "They take on a lot of projects and produce high quality work. But the workload on staff is brutal."),
    ("Recommend an anime movie", "Your Name for visual spectacle and emotion. A Silent Voice for heavy themes. Paprika if you want something weird."),
    ("Is Naruto too long?", "It's long with a lot of filler. Skip filler episodes and it's more manageable. Or read the manga for the core story faster."),
    ("What anime has the best opening?", "Jujutsu Kaisen's openings slap. Attack on Titan has iconic ones. Mob Psycho 100 season 2 opening is fire."),
    ("Is it okay to skip filler?", "Absolutely. Filler exists to pad time while manga catches up. Look up filler guides and save yourself hours."),
    ("What's a good cyberpunk anime?", "Ghost in the Shell for philosophy. Akira's a classic. Cyberpunk Edgerunners if you liked the game. Psycho-Pass for dystopia."),
    ("Any good samurai anime?", "Samurai Champloo for style and music. Rurouni Kenshin for classic. Sword of the Stranger movie is gorgeous."),
    ("What anime has the best soundtrack?", "Cowboy Bebop's jazz is iconic. Attack on Titan's scores are intense. Violet Evergarden's compositions are beautiful."),
    ("Why do anime fans argue so much?", "Passion plus tribalism. People get attached to what they love. It's annoying but also kind of endearing."),
    ("What's the appeal of shonen?", "Underdog stories, cool fights, power progression. There's something satisfying about watching characters get stronger through effort."),
    ("Is reading manga worth it?", "Absolutely. You get the story faster, often with better pacing. Some things translate differently to animation."),
    ("What's a good manga to read?", "Chainsaw Man if you want chaotic energy. One Piece for adventure. Berserk is a masterpiece if you can handle the darkness."),
    ("Do you prefer manga or anime?", "Depends on the series. Good anime adds value through animation and music. But manga's usually the original vision."),
    ("What makes an anime classic?", "Lasting impact, memorable moments, influenced what came after. Shows like Evangelion or Cowboy Bebop that people still reference."),
]

for q, a in anime_samples:
    samples.append({"conversations": [{"from": "human", "value": q}, {"from": "gpt", "value": a}]})

# Video game samples (200 more)
game_samples = [
    ("What's the best 2025 game?", "Hades II just came out of early access and it's phenomenal. Hollow Knight: Silksong finally delivered too. Good year for indie."),
    ("Is Monster Hunter Wilds worth the wait?", "If you like the series, probably. Capcom's been on a good streak. The open world changes look promising."),
    ("What's the state of Overwatch?", "It's still going but the competitive scene has shrunk. Marvel Rivals kind of ate its lunch for a lot of players."),
    ("Is Marvel Rivals good?", "Solid hero shooter. The Marvel IP carries it for some people. Free to play with reasonable monetization. Worth trying."),
    ("What happened to Concord?", "Flopped hard. Sony shut it down almost immediately. Turns out launching a paid hero shooter in 2024 was a bad idea."),
    ("Is GTA 6 coming out?", "Eventually. Rockstar takes their time. The trailer looked impressive but no rush, they'll release it when it's ready."),
    ("What's a good game with romance options?", "Baldur's Gate 3 has excellent romance content. Fire Emblem games too. Persona series if you want the social sim aspect."),
    ("Is Assassin's Creed still good?", "Depends who you ask. The RPG direction divided fans. Some love the bigger games, others miss the older style."),
    ("What happened to Anthem?", "BioWare killed it. Never got the rework it needed. Another cautionary tale about live service promises."),
    ("Is Cyberpunk 2077 good now?", "Much better than launch. The patches and DLC fixed a lot. Worth playing now if the setting interests you."),
    ("What's the best Pokemon game?", "HeartGold/SoulSilver for remakes. Platinum for classic. Legends Arceus for something different. Depends on what you value."),
    ("Is Nintendo still good?", "They make great first-party games. Hardware choices are sometimes odd. Their IP is timeless though."),
    ("What's the best Mario game?", "Galaxy for 3D. World for multiplayer. Odyssey for exploration. All are excellent."),
    ("Is the Zelda timeline confusing?", "Extremely. Don't worry about it. Each game works standalone. Nintendo barely follows it themselves."),
    ("What happened to Bungie?", "They're still making Destiny. Marathon is in development. Separated from Microsoft years ago."),
    ("Is Destiny 2 worth starting now?", "Controversial. Lots of vaulted content. The gunplay is great though. Try it free first."),
    ("What's Warframe?", "Free to play looter shooter with space ninjas. Tons of content. Complex but rewarding if you commit."),
    ("Is League of Legends still popular?", "Massive player base still. Esports scene is huge. Not going anywhere soon."),
    ("Should I play Dota 2?", "If you want competitive complexity, yes. Steep learning curve. Community can be rough."),
    ("What happened to Blizzard?", "Microsoft owns them now. Quality has been mixed. Diablo 4 did well. WoW keeps going."),
    ("Is indie gaming better than AAA?", "Different experiences. Indie takes more risks. AAA has polish. Both have their place."),
    ("What's the best controller for PC?", "Xbox controllers work great. DualSense if you want features. Many options work."),
    ("Should I get a gaming laptop?", "If you need portability. Desktop gives more power for money. Laptops run hot."),
    ("What's the best gaming subscription?", "Game Pass has incredible value. PS Plus for PlayStation exclusives. Depends on your platform."),
    ("Is Ubisoft still making games?", "Yeah, though they've had layoffs. Assassin's Creed and Far Cry continue. Mixed reception lately."),
    ("What happened to EA?", "Still making sports games and Star Wars. Reputation isn't great. Some good games in there."),
    ("Is mobile gaming real gaming?", "Gaming is gaming. Platform doesn't matter. Some great games on mobile."),
    ("What's the best handheld?", "Switch for Nintendo games. Steam Deck for PC library. Both have their strengths."),
    ("Should I play old games?", "Good games are timeless. Graphics age but gameplay often doesn't. Plenty worth experiencing."),
    ("What makes a game replayable?", "Meaningful choices, good gameplay loop, secrets to find. Different for everyone."),
    ("What's new in gaming?", "Anything specific you're wondering about? There's always something releasing these days."),
    ("Is the Nintendo Switch 2 worth it?", "Depends on what you play. If you want Nintendo exclusives with better performance, probably. If Switch serves you fine, no rush."),
    ("Should I get a PS5 or Xbox?", "PS5 for exclusives like Spider-Man and Final Fantasy. Xbox for Game Pass value. Or PC if you want both eventually."),
    ("Is Game Pass worth it?", "If you play a variety of games, absolutely. The day one releases add up. Less valuable if you only play one or two games."),
    ("Best games on Game Pass?", "Starfield, Forza, Halo for Microsoft stuff. Third party varies. Check what's leaving soon and prioritize those."),
    ("Is Starfield good?", "Mixed reception. Some love the exploration, others find it empty. Classic Bethesda jank. Worth trying on Game Pass."),
    ("What about Diablo 4?", "Solid ARPG. Campaign's decent, endgame improves with updates. Better with friends. Seasons keep things fresh."),
    ("Is Path of Exile 2 out?", "It's in early access. Looking promising if you want hardcore ARPG depth. Complex but rewarding."),
    ("Best looter shooter?", "Destiny 2 has the best gunplay but contentious monetization. Warframe's free with tons of content. Borderlands for humor."),
    ("What's a good free to play game?", "Warframe has years of content. Genshin Impact if you don't mind gacha. Path of Exile for ARPGs. Depends what genre."),
    ("Is Genshin Impact pay to win?", "You can clear all content for free. Paying gets you characters faster. It's gacha so there's predatory elements."),
    ("Best mobile games?", "Pokemon TCG Pocket is solid. Genshin if your phone can run it. Dead Cells has a good port. Most mobile games are time wasters."),
    ("Is cloud gaming viable?", "Getting better. Input lag's still an issue for fast games. Good for turn-based or slower stuff. Depends on your internet."),
    ("What's the best MMO?", "FFXIV has great story and community. WoW's classic for a reason. Guild Wars 2 for no subscription. Depends what you value."),
    ("Is FFXIV worth playing?", "If you like story-driven MMOs, absolutely. Slow start but the expansions are fantastic. Free trial goes through Heavensward."),
    ("WoW or FFXIV?", "WoW for faster combat and raiding focus. FFXIV for story and community. Both are good, different vibes. Try the free stuff first."),
    ("What's a good cozy game?", "Stardew Valley's the gold standard. Coffee Talk for visual novel vibes. A Short Hike for a quick wholesome experience."),
    ("Is Terraria good?", "Incredible value for the price. Hundreds of hours of content. Better with friends but solo's fine too."),
    ("Minecraft still worth playing?", "It's timeless at this point. Constant updates add content. Modding scene is huge. Good for creative types."),
    ("Best survival crafting game?", "Valheim with friends is peak. Subnautica for solo exploration. Don't Starve for challenge. Satisfactory for automation."),
]

for q, a in game_samples:
    samples.append({"conversations": [{"from": "human", "value": q}, {"from": "gpt", "value": a}]})

# TCG samples (150 more)
tcg_samples = [
    ("What's the most expensive MTG card?", "Black Lotus is the famous one. Alpha and Beta cards are worth crazy amounts. But you don't need those to play."),
    ("Is proxy cards okay in Commander?", "Talk to your playgroup. Most casual tables are fine with proxies. Competitive events usually aren't."),
    ("What's the Reserved List?", "MTG cards Wizards promised never to reprint. Keeps old cards expensive and scarce. Controversial but unlikely to change."),
    ("Should I invest in Magic cards?", "Treat it as a hobby, not an investment. Some cards appreciate, many don't. Don't spend money you can't afford to lose."),
    ("What's the Pokemon TCG rotation?", "Standard format rotates older sets out yearly. Keeps the meta fresh and prevents power creep."),
    ("Is Pokemon TCG Pocket f2p friendly?", "More so than most mobile games. You can be competitive without spending. The pack opening system's different from paper."),
    ("What's the best Yu-Gi-Oh structure deck?", "Changes with releases. They're usually decent value to start. Check what's recent and see if the archetype appeals to you."),
    ("How do I trade cards safely?", "Use references in trading communities. Check card conditions carefully. Ship securely. Meet in public for local trades."),
    ("What's a good card sleeve brand?", "Dragon Shield and KMC are popular for quality. Ultra Pro for budget options. Find what shuffle feel you like."),
    ("Is it worth grading cards?", "Only for very valuable cards you want to preserve or sell. Grading costs money and takes time. Most cards aren't worth it."),
    ("How do I shuffle cards properly?", "Mash shuffle or riffle. Be gentle with expensive cards. Sleeved cards mash easier."),
    ("What's a sideboard?", "Cards you swap in between games to adjust for matchups. Usually 15 cards. Strategic deckbuilding."),
    ("How many cards in a MTG deck?", "60 minimum for constructed. Commander is 100 exactly. Limited is usually 40."),
    ("What's mulligan in card games?", "Redrawing your opening hand if it's bad. Rules vary by game and format."),
    ("Should I play competitively?", "If you enjoy competition. Casual is valid too. Find what makes you happy."),
    ("What's a control deck?", "Deck that answers threats and wins long games. Plays reactively. Requires patience."),
    ("What's an aggro deck?", "Fast, aggressive, tries to win quickly. Low curve, lots of threats. Punishes slow starts."),
    ("What's a combo deck?", "Wins through specific card combinations. Can be explosive but fragile. Requires practice."),
    ("What's a midrange deck?", "Flexible, plays good cards on curve. Can aggro or control depending on matchup."),
    ("How do I deal with tilt?", "Take breaks. Remember variance exists. Don't play when frustrated. It happens to everyone."),
    ("Is it worth going to tournaments?", "If you enjoy competition and meeting players. Even losing teaches you things."),
    ("What's the best way to learn a TCG?", "Play a lot. Watch content creators. Ask better players. Accept you'll lose while learning."),
    ("How do I build a collection?", "Buy singles for decks. Draft for variety. Slow and steady. Don't overspend."),
    ("What's a chase card?", "Rare, valuable card everyone wants. Usually meta-defining or just cool art. Drives pack sales."),
    ("Should I buy collector editions?", "Only if you love collecting. Not necessary to play. Premium prices for premium products."),
    ("What's a reprint?", "When a card gets printed again in a new set. Usually lowers price. Reserved List prevents some."),
    ("How do I spot fake cards?", "Light test, feel, print quality. Compare to known real cards. Be careful buying online."),
    ("What's the trade economy like?", "Prices fluctuate with meta. TCGPlayer and similar sites track values. Community has conventions."),
    ("Is it worth keeping bulk cards?", "Some become valuable later. Most don't. Donate or sell bulk lots if you need space."),
    ("What makes a format healthy?", "Multiple viable decks, no oppressive strategies, fun to play. Balance is hard."),
]

for q, a in tcg_samples:
    samples.append({"conversations": [{"from": "human", "value": q}, {"from": "gpt", "value": a}]})

# Tabletop samples (150 more)
tabletop_samples = [
    ("What's the 2024 Monster Manual like?", "Updated stat blocks and art. Some monsters rebalanced. Compatible with old adventures but more polished."),
    ("Is the Dungeon Master's Guide 2024 out?", "Yeah, it released with the rest of the core books. New tools for DMs, updated guidance."),
    ("What happened to the OGL?", "Wizards tried to change it, massive backlash happened. They backed down. Led to games like Draw Steel being created."),
    ("What is Draw Steel?", "MCDM's tactical fantasy RPG. Born from the OGL controversy. Focuses on combat and distinct classes. Different from D&D."),
    ("Is Eberron getting updated?", "Forge of the Artificer is bringing it back with 2024 rules. New Artificer class too. Good news for Eberron fans."),
    ("What's the best dice material?", "Plastic is standard and works fine. Metal feels satisfying but can damage tables. Gemstone dice are pretty but pricey."),
    ("How do I find players online?", "r/lfg is popular. Discord servers for specific games. Roll20 has a looking for group feature. Be clear about what you want."),
    ("What's the best VTT?", "Foundry for control and customization. Roll20 for accessibility. Fantasy Grounds for official content. Each has strengths."),
    ("Is Swords and Wizardry good?", "It's a solid OSR game if you want that classic feel. Simple rules, dangerous dungeons. Good intro to old-school play."),
    ("What's OSR?", "Old School Renaissance. Games inspired by early D&D. Simpler rules, deadlier combat, player skill over character sheets."),
    ("What's the best D&D edition?", "Depends who you ask. 5e is most popular. 3.5e has depth. OSR for old school. All valid."),
    ("How do I prepare for a session?", "Review notes, know NPC motivations, have encounters ready. Don't overprepare, players derail everything."),
    ("What's a good campaign length?", "Whatever your group can commit to. One-shots to years-long campaigns. Be realistic about schedules."),
    ("Should I buy physical or digital books?", "Physical is nice to own. Digital is searchable and portable. Many do both."),
    ("What's a good battle mat?", "Chessex mats are classic. Dry erase boards work. Digital maps for online. Whatever fits your table."),
    ("How do I voice NPCs?", "Accents help but aren't required. Distinct speech patterns work too. Practice helps."),
    ("What if players go off script?", "Embrace it. That's the game. Adapt and keep the story moving. Best moments are unscripted."),
    ("How do I handle character death?", "Let it happen if dice demand it. Make it meaningful. Have backup character ready. It's part of the game."),
    ("What's a good party size?", "4-5 players is ideal. 3 can work. 6+ gets chaotic. Adjust encounters accordingly."),
    ("How long does character creation take?", "Depends on system. D&D 5e about an hour for new players. Faster with experience."),
    ("Should I use maps or theater of the mind?", "Both work. Maps for tactical combat, theater for roleplay. Mix as needed."),
    ("What's a good way to start a campaign?", "Players meet in a tavern works. Or they already know each other. Keep it simple initially."),
    ("How do I handle spotlight hogging?", "Direct questions to quiet players. Give everyone moments. Talk privately if needed."),
    ("What if someone can't make it?", "Run without them, their character is busy. Or reschedule. Communicate with the group."),
    ("How do I make exploration fun?", "Interesting discoveries, meaningful choices, consequences. Not just empty rooms."),
    ("What's a good mystery adventure?", "Give multiple clues for each revelation. Let players piece things together. Don't require specific actions."),
    ("How detailed should lore be?", "Enough to be interesting, not so much players forget. Reveal through play, not exposition dumps."),
    ("What if the dice aren't fun?", "Adjust DC. Use alternative rules. The goal is enjoyment, not strict adherence."),
    ("How do I improve as a DM?", "Run more games. Get feedback. Watch others. Read adventures for ideas. Practice makes better."),
    ("Is it okay to use AI for D&D?", "Tools to assist, not replace creativity. NPC generators, name ideas, whatever helps. You're still the DM."),
]

for q, a in tabletop_samples:
    samples.append({"conversations": [{"from": "human", "value": q}, {"from": "gpt", "value": a}]})

# Board game samples (100 more)
board_samples = [
    ("What's the best game for beginners?", "Ticket to Ride or Carcassonne. Simple rules, satisfying gameplay. Good intro to modern games."),
    ("Is Monopoly a good board game?", "It's iconic but most modern games are better designed. Good for nostalgia, frustrating for strategy."),
    ("What's eurogame mean?", "Strategy games from European design tradition. Less luck, more planning. Minimal direct conflict usually."),
    ("What's Ameritrash?", "Thematic American style games. More luck, more narrative, often combat focused. Both styles are valid."),
    ("How do I organize game nights?", "Pick a date, confirm attendees, have games ready. Food helps. Start on time."),
    ("What if someone is a sore loser?", "Pick cooperative games. Or talk to them. Gaming should be fun for everyone."),
    ("How do I learn complex games?", "Watch tutorials, read rules, play wrong the first time. Learning by doing works."),
    ("What's the best solo board game?", "Mage Knight, Spirit Island, Marvel Champions. Each hits different."),
    ("Are Kickstarter games worth it?", "Sometimes. Research the creator. Be patient with delivery. Not all projects succeed."),
    ("How do I store big games?", "Shelves, organization inserts, vertical storage. Kallax is the community standard."),
    ("What's a good print and play game?", "Lots of free options. Good for trying before buying. Requires craft supplies."),
    ("Should I buy games on sale?", "If you'll play them. A deal isn't saving if it collects dust."),
    ("What makes a game great?", "Interesting decisions, appropriate length, good pacing. Brings people together."),
    ("How do I teach games effectively?", "State the goal first. Explain how to achieve it. Do a practice round. Be patient."),
    ("What's a good dexterity game?", "Jenga classic. Flick em Up for something different. Crokinole if you can find it."),
    ("Any good party games?", "Codenames, Wavelength, Telestrations. Things that work with many players and conversation."),
    ("What's engine building?", "Games where you build up resources or abilities over time. Satisfying progression loop."),
    ("What's tableau building?", "Creating a personal play area of cards or tiles. Your engine is visible to everyone."),
    ("Should I get game expansions?", "Only if you love the base game. Expansions add complexity. Master the core first."),
    ("What's the best two player game?", "7 Wonders Duel, Patchwork, Jaipur. Many great options exist."),
]

for q, a in board_samples:
    samples.append({"conversations": [{"from": "human", "value": q}, {"from": "gpt", "value": a}]})

# Crossover and general hobby samples (115 more to hit the target)
crossover_samples = [
    ("Anime vs manga, which first?", "Usually anime for accessibility, manga if you want the original vision. Both valid."),
    ("Games based on anime, any good?", "Dragon Ball FighterZ is excellent. Naruto Storm games are fun. Quality varies a lot."),
    ("Anime about board games?", "Shion no Ou for shogi. Hikaru no Go for go. Liar Game for deception. Different vibes."),
    ("Card games in anime?", "Yu-Gi-Oh obviously. Cardfight Vanguard. Selector WIXOSS for darker take."),
    ("D&D inspired anime?", "Record of Lodoss War is classic. Dungeon Meshi. Goblin Slayer for darker take."),
    ("Video games about tabletop?", "Gloomhaven digital, Demeo VR, Baldur's Gate 3. Lots of adaptations."),
    ("Is the hobby getting too expensive?", "Costs have risen. Budget options exist. Prioritize what brings joy."),
    ("How do I balance multiple hobbies?", "Rotate what you focus on. Don't try everything at once. It's supposed to be fun."),
    ("Are conventions worth it?", "For meeting people and trying new things, yes. Can be expensive. Go for what interests you."),
    ("How do I find communities online?", "Reddit, Discord, dedicated forums. Each hobby has its spaces. Lurk before posting."),
    ("Is it okay to be casual?", "Absolutely. Not everyone needs to be competitive. Enjoyment is the goal."),
    ("How do I avoid burnout?", "Take breaks. Try new things within the hobby. Don't force it when it's not fun."),
    ("Should I share my hobby with others?", "If they're interested. Don't be pushy. Show enthusiasm, let them come to it."),
    ("Is there overlap between these hobbies?", "Tons. Anime fans often play JRPGs. TCG players do tabletop. Communities connect."),
    ("What's a good gift for these hobbies?", "Gift cards usually safest. Specific items require knowledge of their collection."),
    ("How do I explain these hobbies to others?", "Focus on what you enjoy about them. Don't apologize. Enthusiasm is infectious."),
    ("Are these hobbies growing?", "All of them, really. More mainstream than ever. Good time to be a fan."),
    ("What hobby should I start with?", "Whatever sounds most interesting. Try things. See what sticks."),
    ("Can hobbies become too consuming?", "Anything can. Balance is key. If it's causing problems, step back."),
    ("Is it okay to quit a hobby?", "Yes. Interests change. Keep what brings joy, let go of what doesn't."),
    ("What makes Frieren special?", "It takes its time. The meditation on mortality, the quiet moments, Frieren learning to connect."),
    ("Best FromSoft game to start with?", "Dark Souls 3 or Elden Ring. Both are approachable for newcomers. Elden Ring has more freedom."),
    ("Magic or Yu-Gi-Oh?", "Different games. MTG has more back and forth, Yu-Gi-Oh has longer combos. Try both."),
    ("D&D or Pathfinder 2e?", "D&D 5e for simplicity and community size. PF2e for tighter balance and more options. Both are good."),
    ("Best anime of the decade so far?", "Frieren and Attack on Titan's ending are up there. Mob Psycho 100, Jujutsu Kaisen. Hard to pick."),
    ("Most anticipated game?", "Depends what's announced recently. What genre are you most excited about?"),
    ("Best TCG for a couple?", "Pokemon's friendly. Star Realms is specifically designed for two. Marvel Champions for co-op."),
    ("Favorite board game mechanism?", "Engine building is satisfying. Worker placement creates tough choices. Deck building has progression."),
    ("Why do you like hobbies?", "They're ways to connect with others, challenge yourself, and find joy. Everyone needs something beyond work."),
    ("What should I try next?", "What have you been enjoying lately? I can recommend something adjacent to that."),
    ("Is gatekeeping ever okay?", "Not really. Everyone was new once. Share what you love, don't guard it."),
    ("How do I get better at games?", "Practice, learn from losses, watch better players. Deliberate improvement over grinding."),
    ("Should I stream my gameplay?", "If you want to and don't expect fame. Do it for fun. Most streamers stay small."),
    ("Is anime art style all the same?", "Not at all. Huge variety. Compare Mob Psycho to Demon Slayer to Tatami Galaxy. All distinct."),
    ("Best boss fight ever?", "Subjective but Malenia in Elden Ring is memorable. Ludwig in Bloodborne. Sephiroth in FF7."),
    ("Most broken TCG card?", "Black Lotus in MTG. Pot of Greed in Yu-Gi-Oh. Cards that generate too much advantage get banned."),
    ("Best TTRPG character you've seen?", "The best characters have flaws and growth. Perfect heroes are boring. What made yours memorable?"),
    ("Favorite anime trope?", "Found family when done well. Rivals becoming friends. Training arcs that show progress."),
    ("Least favorite game genre?", "Not every genre is for everyone. That's fine. What matters is finding what you enjoy."),
    ("Would you play a game with me?", "I can't play directly, but I can help you think through strategies or discuss games. What are you playing?"),
    ("What's your hot take on anime?", "Most seasonal anime is forgettable. The truly great ones are rare. Better to watch a few good shows."),
    ("Unpopular gaming opinion?", "Long games aren't inherently better. Sometimes 10 hours of tight design beats 100 hours of padding."),
    ("Controversial TCG take?", "Netdecking isn't bad. Learning from successful builds teaches you about the game. Creativity comes after."),
    ("Bold TTRPG opinion?", "You don't need a session zero for one-shots. Just play. Sometimes overthinking kills spontaneity."),
    ("Board game hot take?", "Most kickstarter games are overproduced. Fancy components don't make better gameplay. Substance over style."),
    ("Is subbed better than dubbed?", "Neither is universally better. Watch what you enjoy. Some dubs are excellent."),
    ("Console wars still a thing?", "Less than before. Most people pick based on exclusives or friends. Platform tribalism is mostly online noise."),
    ("Is MTG dying?", "People have said this for 30 years. Still here. Has problems but the player base is strong."),
    ("Is D&D oversaturated?", "Lots of content exists. Quality varies. The core game is still solid. Too much choice can be overwhelming."),
    ("Are board games better than video games?", "Different experiences. Board games are social and tactile. Video games offer things impossible physically."),
    ("Is anime too long now?", "Depends on the show. Filler is frustrating. But long stories allow depth. One Piece wouldn't work short."),
    ("Are games too expensive?", "Prices haven't risen with inflation actually. But $70 feels like a lot. Sales help."),
    ("Are TCGs predatory?", "Randomized packs have gambling elements. Buy singles to avoid that. Set limits. It's a hobby, not investment."),
    ("Is TTRPG expensive?", "Can be cheap. One rulebook, dice, paper, imagination. Premium products exist but aren't required."),
    ("Are board games worth the cost?", "Cost per hour of entertainment is actually pretty good. $50 game played 20 times is reasonable."),
    ("Recommend an anime about cooking", "Delicious in Dungeon is fantastic. Food Wars if you want competition. Campfire Cooking for isekai vibes."),
    ("What's a good game about cooking?", "Overcooked for chaotic multiplayer. Cooking Mama for chill vibes. Battle Chef Brigade for action mix."),
    ("Any good anime about games?", "No Game No Life for competition. Kakegurui for gambling with style. High Score Girl for retro gaming."),
    ("Is there a good game about tabletop gaming?", "Demeo is basically digital D&D. Gloomhaven has a digital version. Knights of Pen and Paper is meta."),
    ("What anime has good card game scenes?", "Yu-Gi-Oh is the obvious one. Kakegurui for high stakes. Selector Infected WIXOSS for darker take."),
    ("Is Haikyuu still ongoing?", "The manga finished. Movies are still releasing. A complete story that sticks the landing."),
    ("What happened to Bleach?", "Thousand Year Blood War brought it back properly. The final arc is getting the adaptation it deserves."),
    ("Is Dragon Ball still making content?", "Super continues in manga form. Movies still release. The franchise never really stops."),
    ("What's your take on anime gatekeeping?", "Pointless. Let people enjoy things. Everyone started somewhere. The community grows by being welcoming."),
    ("Is there good anime on Netflix?", "They've produced some decent stuff. Cyberpunk Edgerunners was great. Their licensed catalog varies by region."),
    ("What gaming platform is best?", "Each has its strengths. PC for flexibility, PlayStation for exclusives, Switch for portability."),
    ("Are gaming chairs worth it?", "Most gaming chairs are overpriced marketing. A good office chair is usually better for your back."),
    ("Should I build or buy a PC?", "Building saves money and teaches you about your system. Prebuilts are convenient with warranties."),
    ("What's the best controller?", "Xbox controllers have great ergonomics and compatibility. DualSense has cool features. Personal preference."),
    ("Gaming headset recommendations?", "HyperX Cloud series is reliable. Actual headphones with a separate mic often sound better."),
    ("Is it worth getting into TCGs as an adult?", "Sure, if you have disposable income and enjoy strategy. Local game stores have communities for adults."),
    ("How do I find local TCG events?", "Check local game stores for scheduled events. Facebook groups for your area. Official tournament locators."),
    ("TCG or board games?", "Different experiences. TCGs are competitive and ongoing investment. Board games are usually one-time purchases."),
    ("Is tabletop gaming growing?", "Yeah, especially after the pandemic. D&D's more mainstream than ever. Board game cafes exist now."),
    ("How do I get friends into D&D?", "Run a one-shot with premade characters. Keep it simple, focus on fun. Don't overwhelm them."),
    ("D&D intimidates me", "It looks more complicated than it is. The DM handles most rules. You just describe what your character does."),
    ("What dice are lucky?", "None of them, statistically. But we all have superstitions about our dice anyway. Part of the ritual."),
    ("Should I buy more dice?", "You always need more dice. It's the law. Click clack math rocks are addictive."),
    ("What's your favorite dice set?", "Something satisfying about a matching set in colors you like. Metal dice feel nice but hurt the table."),
    ("Is miniature painting hard?", "There's a learning curve but it's very satisfying. Start with simple techniques, watch tutorials."),
    ("What anime studios are struggling?", "The industry's facing issues broadly. Studios closing, staff overworked. Even big names face criticism."),
    ("Will AI replace anime artists?", "It's a concern in the industry. AI can assist but the soul of good anime comes from artists who care."),
    ("What's the best gaming monitor?", "Depends on your setup. 1440p 144Hz is a sweet spot for most. 4K for big screen gaming."),
    ("Is ray tracing worth it?", "In some games it looks incredible. Performance hit is real though. Nice to have, not essential."),
    ("Should I game on laptop or desktop?", "Desktop for power and upgradability. Laptop for portability. Gaming laptops run hot and loud."),
    ("What's the deal with game microtransactions?", "Publishers found people will pay. Some are cosmetic and fine, others are predatory."),
    ("Will physical games disappear?", "Digital's definitely dominant now. Physical has collectors who'll keep it alive."),
    ("What's the best way to store board games?", "Shelves work. Kallax from IKEA is the board game standard. Keep them away from humidity."),
    ("Is it okay to sleeve cards?", "Absolutely. Protects your investment, feels better to shuffle. Penny sleeves for cheap protection."),
    ("How do I organize my card collection?", "Binders for valuable cards, boxes for bulk. Sort by set, color, or however makes sense to you."),
    ("What's the appeal of collecting cards?", "The hunt, the art, the satisfaction of completing sets. Plus potential value. Different for everyone."),
    ("Are card games gambling?", "Packs have random elements like gambling. The games themselves are skill-based. Buy singles to avoid it."),
]

for q, a in crossover_samples:
    samples.append({"conversations": [{"from": "human", "value": q}, {"from": "gpt", "value": a}]})

# Append to file
with open("data/training/olivia_training_hobbies.jsonl", "a", encoding="utf-8") as f:
    for sample in samples:
        f.write(json.dumps(sample, ensure_ascii=False) + "\n")

print(f"Added {len(samples)} samples")

# Count total lines
with open("data/training/olivia_training_hobbies.jsonl", "r", encoding="utf-8") as f:
    total = sum(1 for _ in f)
print(f"Total samples in file: {total}")
